package org.bian.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.bian.dto.CRProspectCampaignSpecificationCaptureInputModelProspectCampaignSpecificationInstanceRecordProspectCampaignPerformanceRecordProspectCampaignProcedureInstanceReference;

import javax.validation.Valid;
  
/**
 * CRProspectCampaignSpecificationCaptureInputModelProspectCampaignSpecificationInstanceRecordProspectCampaignPerformanceRecord
 */
public class CRProspectCampaignSpecificationCaptureInputModelProspectCampaignSpecificationInstanceRecordProspectCampaignPerformanceRecord   {
  private CRProspectCampaignSpecificationCaptureInputModelProspectCampaignSpecificationInstanceRecordProspectCampaignPerformanceRecordProspectCampaignProcedureInstanceReference prospectCampaignProcedureInstanceReference = null;


  /**
   * Get prospectCampaignProcedureInstanceReference
   * @return prospectCampaignProcedureInstanceReference
  **/

  public CRProspectCampaignSpecificationCaptureInputModelProspectCampaignSpecificationInstanceRecordProspectCampaignPerformanceRecordProspectCampaignProcedureInstanceReference getProspectCampaignProcedureInstanceReference() {
    return prospectCampaignProcedureInstanceReference;
  }

  public void setProspectCampaignProcedureInstanceReference(CRProspectCampaignSpecificationCaptureInputModelProspectCampaignSpecificationInstanceRecordProspectCampaignPerformanceRecordProspectCampaignProcedureInstanceReference prospectCampaignProcedureInstanceReference) {
    this.prospectCampaignProcedureInstanceReference = prospectCampaignProcedureInstanceReference;
  }


}

